include:
  - board: xiao_ble//zmk
    shield: eyelash_sofle_central_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2.0.0//zmk
    shield: eyelash_sofle_peripheral_left nice_view_adapter nice_view_gem
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano@2.0.0//zmk
    shield: eyelash_sofle_peripheral_right nice_view_adapter nice_view_gem
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano@2.0.0//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: settings_reset